In [ ]:
import torch
random_image_size=torch.rand(3,224,224)
random_image_size.float()
arange=torch.arange(10,90,10)
arange=arange.reshape(4,2)
zeroes=torch.zeros_like(input=arange)
zeroes

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])

important attributes to get info of tensors:
1.Tensor not right datatype- tensor.dtype
2.Tensornot in right shape- tensor.shape
3. Tensor not  in right device- tensor.device

In [ ]:
tensor=torch.tensor([1,2,3])
print(tensor.dtype)
print(tensor.shape)
print(tensor.device)
print(tensor)
tensor

torch.int64
torch.Size([3])
cpu
tensor([1, 2, 3])


tensor([1, 2, 3])

In [ ]:
#Manipulating tensors(arithmetic)
print(tensor)
print(tensor+10)
print(tensor)
tensor.add_(10)
print(tensor)
t1=torch.rand(4,4)
t2=torch.rand(4,4)
t3=t1+t2
t4=t1*t2
t5=t1/t2
t6=t1**3
print(t1)
print(t2)
print(t3)
print(t4)
print(t5)
print(t6)


tensor([11, 12, 13])
tensor([21, 22, 23])
tensor([11, 12, 13])
tensor([21, 22, 23])
tensor([[0.9079, 0.6158, 0.5213, 0.3374],
        [0.6546, 0.0971, 0.2394, 0.6994],
        [0.5635, 0.7219, 0.9315, 0.5236],
        [0.8294, 0.6254, 0.8453, 0.0409]])
tensor([[0.8812, 0.8539, 0.9418, 0.1187],
        [0.3612, 0.4141, 0.0571, 0.0354],
        [0.0652, 0.4062, 0.7395, 0.9664],
        [0.5429, 0.0821, 0.4617, 0.2385]])
tensor([[1.7891, 1.4698, 1.4631, 0.4562],
        [1.0158, 0.5112, 0.2965, 0.7348],
        [0.6287, 1.1281, 1.6710, 1.4900],
        [1.3723, 0.7074, 1.3071, 0.2794]])
tensor([[0.8000, 0.5259, 0.4910, 0.0401],
        [0.2365, 0.0402, 0.0137, 0.0248],
        [0.0368, 0.2932, 0.6889, 0.5060],
        [0.4503, 0.0513, 0.3903, 0.0098]])
tensor([[ 1.0303,  0.7212,  0.5536,  2.8420],
        [ 1.8120,  0.2344,  4.1947, 19.7426],
        [ 8.6390,  1.7774,  1.2596,  0.5418],
        [ 1.5278,  7.6193,  1.8309,  0.1714]])
tensor([[7.4837e-01, 2.3356e-01, 1.4169e-01, 3.8420e-02

In [ ]:
#matix opratios
#1.element-wis multiplication
tensor=torch.tensor([1,2,3])
print("element-wise:",tensor*tensor)
#2.matrix multiplication(dot)
print("matrix multiplication:",torch.matmul(tensor,tensor))

element-wise: tensor([1, 4, 9])
matrix multiplication: tensor(14)


In [ ]:
%%time
torch.matmul(tensor,tensor)#or tensor @ tensor

CPU times: user 763 µs, sys: 0 ns, total: 763 µs
Wall time: 614 µs


tensor(14)

In [ ]:
%%time
value=0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 1.61 ms, sys: 0 ns, total: 1.61 ms
Wall time: 2.3 ms


main rules of matrix multiplication: the inner dimesnaions must match:
example
*   (3,2) @ (3,2) will not work
*   (2,3) @ (3,2) will work--->(2,2)
*   (3,2) @ (2,3) will work--->(3,3)
*   (3,3) @ (3,3) will work--->(3,3)

**hence we use a new method called transpose iin case of 3*2 and 3*2 where we transposeoone of them to 2*3**



In [ ]:
tensor1=torch.rand(3,2)
tensor2=torch.rand(3,2)
#torch.matmul(tensor1,tensor2) cause error
tensor2=tensor2.T#here it takes shape form 3*2 to 2*3
torch.matmul(tensor1,tensor2).shape

torch.Size([3, 3])

# Aggregation functions
* Min - tensor.min()  or torch.min(tensor)
* Max - tensor.max()  or torch.max(tensor)
* Mean - tensor.mean() or torch.mean(tensor) ! cannot handle a long tensor like int64
* Sum - tensor.sum() or torch.sum(tensor)
* Position of max - tensor.argmax()
* Position of min -  tensor.argmin()




# Reshaping,Stacking,Squeezing,Unsqueezing and permute

*   Reshape - reshaping a tensor into a certain shape - tensor.reshape(x,y,z)
*   View - Return a view of an input tensor of certain shape but  keep thhe same memory as the origina tensor
* Stacking - combine multiple tensors on top of each other(vstack) or side by side(hstatck)
* Squeeze   - removes all `1` dimensions from a tensor
* Unsqueeze add a `1` dimesion to a tensor
* Premute -  Return a view of the input wiht dimensiones permuted(swaped) in a certain way

In [ ]:
 import torch
x=torch.arange(1,20,2)
x.shape
print(x)
print("x:reshape",x.reshape(5,2))
print("x after reshape:",x)
#VIEW
z=x.view(2,5)#z is given as a view now z shares x's memory
print("z:\n",z)
z[: ,1:2]=99
print("x after changing element in z:\n",x)#whatever change made in z will be made in x
#STACK
x_vstacked=torch.stack([x,x,x,x],dim=0)
x_hstacked=torch.stack([x,x,x,x],dim=1)
print("x_vstacked:\n",x_vstacked)
print("x_hstacked:\n",x_hstacked)
#SQUEEZE
tensor=torch.rand(1,5)
print("tensor:\n",tensor)
print("tensor.shape:",tensor.shape)
tensor_squeezed=tensor.squeeze()
print("tensor_squeezed:\n",tensor_squeezed)
#UNSQUEEZED
tensor_unsqueezed=tensor_squeezed.unsqueeze(dim=1)
print("tensor_unsqueezed\n",tensor_unsqueezed)
#PERMUTE
x=torch.rand(1,2,3)
print("x shape:",x.shape)
x_permuted=x.permute(1,2,0)
print("x permuted shpe:",x_permuted.shape)
print("x:\n",x)
print("_permuted\n",x_permuted)

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])
x:reshape tensor([[ 1,  3],
        [ 5,  7],
        [ 9, 11],
        [13, 15],
        [17, 19]])
x after reshape: tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])
z:
 tensor([[ 1,  3,  5,  7,  9],
        [11, 13, 15, 17, 19]])
x after changing element in z:
 tensor([ 1, 99,  5,  7,  9, 11, 99, 15, 17, 19])
x_vstacked:
 tensor([[ 1, 99,  5,  7,  9, 11, 99, 15, 17, 19],
        [ 1, 99,  5,  7,  9, 11, 99, 15, 17, 19],
        [ 1, 99,  5,  7,  9, 11, 99, 15, 17, 19],
        [ 1, 99,  5,  7,  9, 11, 99, 15, 17, 19]])
x_hstacked:
 tensor([[ 1,  1,  1,  1],
        [99, 99, 99, 99],
        [ 5,  5,  5,  5],
        [ 7,  7,  7,  7],
        [ 9,  9,  9,  9],
        [11, 11, 11, 11],
        [99, 99, 99, 99],
        [15, 15, 15, 15],
        [17, 17, 17, 17],
        [19, 19, 19, 19]])
tensor:
 tensor([[0.0502, 0.7218, 0.3126, 0.9871, 0.5244]])
tensor.shape: torch.Size([1, 5])
tensor_squeezed:
 tensor([0.0502, 0.7218, 0.3126, 0.9871,

# INDEXING
indexing in Pytorch is similar to indexing in numPy

In [ ]:
import torch
x=torch.arange(0,27).reshape(3,3,3)
print(x)
print("selecting all\n:",x[:,:,:])
print("\nselecting first row first row:\n",x[0:1,0:1,:])
print("\nSelecting first two rows of second row:\n",x[1:2,0:2,:])
print("\n selecting first term of first row of last row:\n",x[-1,0:1,0])
print("\n selecting 3rd column of all three rows of first row:\n",x[0,:,-1])
print("\n Selecting 1st column of all thress rows\n:",x[:,:,0])
print('\n Selecting 2 columns from each row\n:',x[:,:,0:2])
print("\n Selecting the middle element of each row\n:",x[:,1:2,1:2])

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])
selecting all
: tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])

selecting first row first row:
 tensor([[[0, 1, 2]]])

Selecting first two rows of second row:
 tensor([[[ 9, 10, 11],
         [12, 13, 14]]])

 selecting first term of first row of last row:
 tensor([18])

 selecting 3rd column of all three rows of first row:
 tensor([2, 5, 8])

 Selecting 1st column of all thress rows
: tensor([[ 0,  3,  6],
        [ 9, 12, 15],
        [18, 21, 24]])

 Selecting 2 columns from each row
: tensor([[[ 0,  1],
         [ 3,  4],
         [ 6,  7]],

        [[ 9, 10],
         [12, 13],
         [15, 16]],

        [

# Pytorch and NumPY
*  numpy data in tensor-->`tensor.from_numpy(array)`
*  Pytorch tensor to numpy--->`torch.Tensor.numpy()`

In [ ]:
import torch
import numpy as np
array=np.arange(0.0,10.0,2)
tensor=torch.arange(0.0,10.0,2)
print(array)
print(tensor)
print("array dtype:",array.dtype)
print("Tensor dtype:",tensor.dtype)
#hence we do this
tensor=torch.from_numpy(array)
print("Tensor dataype:",tensor.dtype)
array=array+1
array,tensor#by changing array it doenst change tensor hence not a view type behavour


[0. 2. 4. 6. 8.]
tensor([0., 2., 4., 6., 8.])
array dtype: float64
Tensor dtype: torch.float32
Tensor dataype: torch.float64


(array([1., 3., 5., 7., 9.]),
 tensor([0., 2., 4., 6., 8.], dtype=torch.float64))

# REPRODUCIBILITY
Trying to take random out of random
* start with random numbers
* tensor operations
* update random numbers to try and make them better reperesentation of the data
* again and
* again

To reduce the randomnes in neural networks and pYtorch comes the concept of a **random seed**
*  you give r random seed intilizing
*  then attach it to `torch.manual_seed(seednumber)`
*  call this everytime u create a random tensor which u want to have same random numbers


In [ ]:
R_A=torch.rand(3,4)
R_B=torch.rand(3,4)
print(R_A==R_B)
#hence we use torch.manual_seed(random-seed)
random_seed=12
torch.manual_seed(random_seed)
R_C=torch.rand(3,4)
torch.manual_seed(random_seed)#each time u create a random tensor call the seeed
R_D=torch.rand(3,4)
print(R_C==R_D)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Accessing a GPU:

**GPU**: faster computation on numbers ,CUDA + NVIDIA harware + Pytorch working makes everything easy and good

In [ ]:
!nvidia-smi


Fri Jan 30 17:12:50 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   39C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
#check gpu access w pytorch
import torch
torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code
device="cuda" if torch.cuda.is_available else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

# Setting up device

In [ ]:
# Putting tensors on GPU
tensor=torch.tensor([1,2,3])
tensor=tensor.to(device)
tensor.device

device(type='cuda', index=0)

In [ ]:
# Moving tensor back to cpu
tensor=tensor.cpu()
tensor.device

device(type='cpu')